"""v2.0 M7 — Generate PDF Laporan Gabungan (Kuitansi + Pengeluaran) per sabat.

Section:
1. Header FLIPUS branding (re-use _build_header_table dari pdf_generator)
2. Title LAPORAN GABUNGAN PENERIMAAN & PENGELUARAN
3. Tabel Kuitansi (X, PT, Khusus, Total, Porsi Misi, Porsi Jemaat) + grand total
4. Tabel Pengeluaran (No, No. Pengeluaran, Kategori, Penerima, Jumlah, Status) + total
5. Ringkasan: Total Penerimaan, Total Pengeluaran, Net Saldo (Penerimaan - Pengeluaran), Penyaluran (Misi, Jemaat)
6. Footer: generated by FLIPUS
"""
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.models.pengeluaran import Pengeluaran
from app.models.tenant import Tenant
from app.models.transaction import Kuitansi
from app.services.pdf_generator import _build_header_table, _build_styles, _get_logo_image, _get_tenant_colors
from app.utils.number_to_words import terbilang


def generate_gabungan_pdf(
    kuitansi_list: list[Kuitansi],
    pengeluaran_list: list[Pengeluaran],
    tenant: Tenant,
    id_rekap_mingguan: str,
    tanggal_sabat_iso: str,
    kategori_map: dict,
    output_path: str | None = None,
) -> bytes:
    """Generate PDF gabungan Kuitansi + Pengeluaran per sabat.

    Args:
        kuitansi_list: Kuitansi (finalized/approved) untuk sabat ini
        pengeluaran_list: Pengeluaran (approved) untuk sabat ini
        tenant: Tenant object (untuk header branding)
        id_rekap_mingguan: mis. 'RK-20260822'
        tanggal_sabat_iso: ISO date sabat
        kategori_map: {kategori_pengeluaran_id: KategoriPengeluaran} — untuk lookup nama
        output_path: kalau diisi, save ke file. Kalau None, return bytes.

    Returns:
        bytes PDF atau path jika output_path diisi.
    """
    primary_color, secondary_color = _get_tenant_colors(tenant)
    logo_image = _get_logo_image(tenant)
    styles = _build_styles(primary_color)

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=1.5 * cm,
        bottomMargin=1.5 * cm,
    )

    elements = []

    # === HEADER ===
    elements.append(_build_header_table(
        uni_name=tenant.nama_uni,
        misi_name=tenant.nama_kantor_misi,
        jemaat_name=tenant.nama_jemaat_lokal,
        primary_color=primary_color,
        logo_image=logo_image,
    ))
    elements.append(Spacer(1, 8))

    # Title
    elements.append(Paragraph(
        "<b>LAPORAN GABUNGAN PENERIMAAN &amp; PENGELUARAN</b>",
        ParagraphStyle("title", parent=styles["HeaderTitle"], fontSize=13),
    ))
    elements.append(Paragraph(
        f"ID Rekap: <b>{id_rekap_mingguan}</b> &nbsp;&nbsp;|&nbsp;&nbsp; "
        f"Tanggal Sabat: <b>{tanggal_sabat_iso}</b> &nbsp;&nbsp;|&nbsp;&nbsp; "
        f"Jemaat: <b>{tenant.nama_jemaat_lokal or '?'}</b>",
        styles["HeaderSubtitle"],
    ))
    elements.append(Spacer(1, 12))

    # === BAGIAN 1: PENERIMAAN (Kuitansi) ===
    elements.append(Paragraph(
        f"<b>A. PENERIMAAN (Kuitansi)</b> — {len(kuitansi_list)} transaksi",
        ParagraphStyle("section", parent=styles["HeaderTitle"], fontSize=11, textColor=primary_color),
    ))
    elements.append(Spacer(1, 4))

    if kuitansi_list:
        data_k = [["No", "No. Kuitansi", "X", "PT", "Khusus", "Total", "Misi", "Jemaat"]]
        sum_x = sum_pt = sum_khusus = sum_misi = sum_jemaat = 0
        for idx, k in enumerate(kuitansi_list, 1):
            total_p = k.total_pemberian_angka or 0
            data_k.append([
                str(idx),
                k.nomor_kuitansi or "",
                f"{k.perpuluhan_x_angka or 0:,}",
                f"{k.pt_angka or 0:,}",
                f"{k.khusus_angka or 0:,}",
                f"{total_p:,}",
                f"{k.porsi_kantor_misi or 0:,}",
                f"{k.porsi_kas_jemaat or 0:,}",
            ])
            sum_x += k.perpuluhan_x_angka or 0
            sum_pt += k.pt_angka or 0
            sum_khusus += k.khusus_angka or 0
            sum_misi += k.porsi_kantor_misi or 0
            sum_jemaat += k.porsi_kas_jemaat or 0
        # FASE 2 S1/R2: konservasi uang — khusus harus masuk total
        total_penerimaan = sum_x + sum_pt + sum_khusus
        data_k.append([
            "", "TOTAL", f"{sum_x:,}", f"{sum_pt:,}", f"{sum_khusus:,}",
            f"{total_penerimaan:,}", f"{sum_misi:,}", f"{sum_jemaat:,}",
        ])

        t_k = Table(
            data_k,
            colWidths=[0.8 * cm, 3.8 * cm, 1.7 * cm, 1.7 * cm, 1.7 * cm, 2.0 * cm, 1.8 * cm, 1.8 * cm],
            repeatRows=1,
        )
        t_k.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), primary_color),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("ALIGN", (0, 0), (0, -1), "CENTER"),
            ("ALIGN", (2, 0), (-1, -1), "RIGHT"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
            ("BACKGROUND", (0, -1), (-1, -1), colors.lightgrey),
            ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -2), [colors.white, colors.HexColor("#fafafa")]),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(t_k)
    else:
        elements.append(Paragraph(
            "<i>(Tidak ada kuitansi untuk sabat ini.)</i>",
            styles["Normal"],
        ))
    elements.append(Spacer(1, 12))

    # === BAGIAN 2: PENGELUARAN ===
    elements.append(Paragraph(
        f"<b>B. PENGELUARAN</b> — {len(pengeluaran_list)} transaksi (approved)",
        ParagraphStyle("section", parent=styles["HeaderTitle"], fontSize=11, textColor=primary_color),
    ))
    elements.append(Spacer(1, 4))

    if pengeluaran_list:
        data_p = [["No", "No. Pengeluaran", "Kategori", "Penerima", "Jumlah", "Status"]]
        sum_pengeluaran = 0
        for idx, p in enumerate(pengeluaran_list, 1):
            kat = kategori_map.get(p.kategori_pengeluaran_id)
            kat_nama = kat.nama if kat else f"#{p.kategori_pengeluaran_id}"
            jml = p.jumlah or 0
            status_label = {
                "approved": "Disetujui",
                "approved_ketua": "Approved Ketua",
                "pending_approval": "Pending",
                "draft": "Draft",
                "rejected": "Ditolak",
            }.get(p.status, p.status)
            data_p.append([
                str(idx),
                p.nomor_pengeluaran or "",
                kat_nama[:18],
                (p.penerima or "-")[:18],
                f"{jml:,}",
                status_label,
            ])
            if p.status == "approved":
                sum_pengeluaran += jml
        data_p.append(["", "TOTAL", "", "", f"{sum_pengeluaran:,}", ""])

        t_p = Table(
            data_p,
            colWidths=[0.8 * cm, 3.5 * cm, 3.5 * cm, 3.5 * cm, 2.5 * cm, 2.5 * cm],
            repeatRows=1,
        )
        t_p.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), primary_color),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("ALIGN", (0, 0), (0, -1), "CENTER"),
            ("ALIGN", (4, 0), (4, -1), "RIGHT"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
            ("BACKGROUND", (0, -1), (-1, -1), colors.lightgrey),
            ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -2), [colors.white, colors.HexColor("#fafafa")]),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(t_p)
    else:
        elements.append(Paragraph(
            "<i>(Tidak ada pengeluaran untuk sabat ini.)</i>",
            styles["Normal"],
        ))
    elements.append(Spacer(1, 14))

    # === BAGIAN 3: RINGKASAN ===
    elements.append(Paragraph(
        "<b>C. RINGKASAN KEUANGAN</b>",
        ParagraphStyle("section", parent=styles["HeaderTitle"], fontSize=11, textColor=primary_color),
    ))
    elements.append(Spacer(1, 4))

    total_penerimaan_final = sum((k.total_pemberian_angka or 0) for k in kuitansi_list)
    total_pengeluaran_final = sum(
        (p.jumlah or 0) for p in pengeluaran_list if p.status == "approved"
    )
    net_saldo = total_penerimaan_final - total_pengeluaran_final
    sum_misi_final = sum((k.porsi_kantor_misi or 0) for k in kuitansi_list)
    sum_jemaat_final = sum((k.porsi_kas_jemaat or 0) for k in kuitansi_list)

    ringkasan_data = [
        ["Total Penerimaan (Kuitansi)", f"Rp {total_penerimaan_final:,}"],
        ["Total Pengeluaran (Approved)", f"Rp {total_pengeluaran_final:,}"],
        ["Net Saldo (Penerimaan − Pengeluaran)", f"Rp {net_saldo:,}"],
        ["", ""],
        ["Penyaluran — Kantor Misi", f"Rp {sum_misi_final:,}"],
        ["Penyaluran — Kas Jemaat", f"Rp {sum_jemaat_final:,}"],
        ["", ""],
        ["Terbilang (Net Saldo)", terbilang(net_saldo) + " rupiah"],
    ]
    t_r = Table(ringkasan_data, colWidths=[8 * cm, 7 * cm])
    t_r.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("ALIGN", (1, 0), (1, -1), "RIGHT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LINEBELOW", (0, 0), (-1, 2), 0.3, colors.grey),
        ("LINEBELOW", (0, 5), (-1, 5), 0.3, colors.grey),
        ("FONTNAME", (0, 2), (-1, 2), "Helvetica-Bold"),
        ("FONTNAME", (1, 2), (1, 2), "Helvetica-Bold"),
        ("BACKGROUND", (0, 2), (-1, 2), colors.HexColor("#fff8dc")),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    elements.append(t_r)
    elements.append(Spacer(1, 12))

    # === FOOTER ===
    elements.append(Paragraph(
        f"<i>Laporan ini digenerate otomatis oleh FLIPUS pada "
        f"{__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')} "
        f"(ID: {id_rekap_mingguan}). Dokumen ini untuk audit internal jemaat & misi.</i>",
        ParagraphStyle("footer", parent=styles["Normal"], fontSize=8, textColor=colors.grey, alignment=TA_CENTER),
    ))

    doc.build(elements)

    pdf_bytes = buffer.getvalue()
    buffer.close()

    if output_path:
        with open(output_path, "wb") as f:
            f.write(pdf_bytes)
        return output_path

    return pdf_bytes
