"""baseline_initial_schema

Revision ID: 72aa8524f06d
Revises: 
Create Date: 2026-09-06 10:18:10.406229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72aa8524f06d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persentase_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=False),
    sa.Column('pct_x_jemaat', sa.Float(), nullable=True),
    sa.Column('pct_pt_jemaat', sa.Float(), nullable=True),
    sa.Column('pct_khusus_jemaat', sa.Float(), nullable=True),
    sa.Column('pct_x_uni', sa.Float(), nullable=True),
    sa.Column('pct_pt_uni', sa.Float(), nullable=True),
    sa.Column('pct_khusus_uni', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persentase_config_ref_id'), 'persentase_config', ['ref_id'], unique=False)
    op.create_index(op.f('ix_persentase_config_scope'), 'persentase_config', ['scope'], unique=False)
    op.create_table('uni',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kode', sa.String(length=8), nullable=False),
    sa.Column('nama_resmi', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    op.create_table('wa_sessions',
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('phone')
    )
    op.create_index('ix_wa_sessions_expires', 'wa_sessions', ['expires_at'], unique=False)
    op.create_index('ix_wa_sessions_state', 'wa_sessions', ['state'], unique=False)
    op.create_table('misi_konferens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uni_id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=16), nullable=False),
    sa.Column('nama_resmi', sa.String(length=255), nullable=False),
    sa.Column('jenis', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['uni_id'], ['uni.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    op.create_index(op.f('ix_misi_konferens_uni_id'), 'misi_konferens', ['uni_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_signature', sa.String(length=64), nullable=False),
    sa.Column('nama_uni', sa.String(length=120), nullable=False),
    sa.Column('nama_kantor_misi', sa.String(length=120), nullable=False),
    sa.Column('nama_jemaat_lokal', sa.String(length=120), nullable=False),
    sa.Column('nama_pendeta', sa.String(length=120), nullable=True),
    sa.Column('nama_ketua_keuangan', sa.String(length=120), nullable=True),
    sa.Column('nama_bendahara', sa.String(length=120), nullable=True),
    sa.Column('initial_jemaat', sa.String(length=4), nullable=True),
    sa.Column('misi_konferens_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=80), nullable=True),
    sa.Column('subdomain', sa.String(length=80), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=False),
    sa.Column('secondary_color', sa.String(length=7), nullable=False),
    sa.Column('footer_text', sa.String(length=255), nullable=True),
    sa.Column('branding_updated_at', sa.DateTime(), nullable=True),
    sa.Column('branding_updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['branding_updated_by'], ['users.id'], name='fk_tenants_branding_updated_by_alter', use_alter=True),
    sa.ForeignKeyConstraint(['misi_konferens_id'], ['misi_konferens.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name='fk_tenants_owner_user_alter', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tenant_uni_misi', 'tenants', ['nama_uni', 'nama_kantor_misi'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_index(op.f('ix_tenants_subdomain'), 'tenants', ['subdomain'], unique=True)
    op.create_index(op.f('ix_tenants_tenant_signature'), 'tenants', ['tenant_signature'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id_rekap_mingguan', sa.String(length=64), nullable=True),
    sa.Column('nomor_kuitansi_token', sa.String(length=32), nullable=True),
    sa.Column('porsi_dana_misi', sa.BigInteger(), nullable=True),
    sa.Column('verifikasi_sintaks_ai', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id_rekap_mingguan'), 'audit_logs', ['id_rekap_mingguan'], unique=False)
    op.create_index(op.f('ix_audit_logs_nomor_kuitansi_token'), 'audit_logs', ['nomor_kuitansi_token'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('kategori_pemasukan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('alias', sa.String(length=8), nullable=False),
    sa.Column('urutan', sa.Integer(), nullable=True),
    sa.Column('is_rutin', sa.Boolean(), nullable=True),
    sa.Column('is_aktif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'alias', name='uq_kategori_pemasukan_tenant_alias')
    )
    op.create_index('ix_kategori_pemasukan_tenant_active', 'kategori_pemasukan', ['tenant_id', 'is_aktif'], unique=False)
    op.create_index(op.f('ix_kategori_pemasukan_tenant_id'), 'kategori_pemasukan', ['tenant_id'], unique=False)
    op.create_table('kategori_pengeluaran',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('alias', sa.String(length=8), nullable=False),
    sa.Column('urutan', sa.Integer(), nullable=True),
    sa.Column('is_rutin', sa.Boolean(), nullable=True),
    sa.Column('is_aktif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'alias', name='uq_kategori_pengeluaran_tenant_alias')
    )
    op.create_index('ix_kategori_pengeluaran_tenant_active', 'kategori_pengeluaran', ['tenant_id', 'is_aktif'], unique=False)
    op.create_index(op.f('ix_kategori_pengeluaran_tenant_id'), 'kategori_pengeluaran', ['tenant_id'], unique=False)
    op.create_table('sync_outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.String(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('pulled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_outbox_created_at'), 'sync_outbox', ['created_at'], unique=False)
    op.create_index(op.f('ix_sync_outbox_payload_hash'), 'sync_outbox', ['payload_hash'], unique=False)
    op.create_index('ix_sync_outbox_tenant_created', 'sync_outbox', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_sync_outbox_tenant_id'), 'sync_outbox', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=120), nullable=False),
    sa.Column('nomor_whatsapp', sa.String(length=32), nullable=True),
    sa.Column('nomor_whatsapp_encrypted', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_secret_encrypted', sa.String(length=255), nullable=True),
    sa.Column('backup_codes_hashed', sa.JSON(), nullable=True),
    sa.Column('twofa_enabled_at', sa.DateTime(), nullable=True),
    sa.Column('last_2fa_used_at', sa.DateTime(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('blast_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('id_rekap_mingguan', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('target_phone', sa.String(length=32), nullable=True),
    sa.Column('fonnte_response', sa.JSON(), nullable=True),
    sa.Column('error_reason', sa.String(length=255), nullable=True),
    sa.Column('pdf_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_blast_jobs_idem')
    )
    op.create_index(op.f('ix_blast_jobs_id_rekap_mingguan'), 'blast_jobs', ['id_rekap_mingguan'], unique=False)
    op.create_index('ix_blast_jobs_rekap', 'blast_jobs', ['id_rekap_mingguan', 'tenant_id'], unique=False)
    op.create_index(op.f('ix_blast_jobs_tenant_id'), 'blast_jobs', ['tenant_id'], unique=False)
    op.create_table('kuitansi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id_rekap_mingguan', sa.String(length=64), nullable=False),
    sa.Column('nomor_kuitansi', sa.String(length=32), nullable=False),
    sa.Column('tanggal_sabat', sa.String(length=16), nullable=False),
    sa.Column('nama_umat_encrypted', sa.String(), nullable=True),
    sa.Column('nomor_whatsapp_encrypted', sa.String(), nullable=True),
    sa.Column('foto_amplop_path', sa.String(), nullable=True),
    sa.Column('is_purged', sa.Boolean(), nullable=True),
    sa.Column('perpuluhan_x_angka', sa.BigInteger(), nullable=True),
    sa.Column('pt_angka', sa.BigInteger(), nullable=True),
    sa.Column('khusus_angka', sa.BigInteger(), nullable=True),
    sa.Column('total_pemberian_angka', sa.BigInteger(), nullable=True),
    sa.Column('total_pemberian_huruf', sa.String(length=255), nullable=True),
    sa.Column('porsi_kantor_misi', sa.BigInteger(), nullable=True),
    sa.Column('porsi_kas_jemaat', sa.BigInteger(), nullable=True),
    sa.Column('porsi_khusus_misi', sa.BigInteger(), nullable=True),
    sa.Column('porsi_khusus_jemaat', sa.BigInteger(), nullable=True),
    sa.Column('porsi_x_uni', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('porsi_pt_uni', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('porsi_khusus_uni', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('porsi_recomputed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by_user_id', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_reason', sa.String(length=500), nullable=True),
    sa.Column('staging_id', sa.Integer(), nullable=True),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('created_via', sa.String(length=16), nullable=False),
    sa.Column('wa_message_id', sa.String(length=64), nullable=True),
    sa.Column('wa_sender', sa.String(length=32), nullable=True),
    sa.Column('sabat_sesi', sa.String(length=16), nullable=True),
    sa.Column('temp_nomor', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rejected_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kuitansi_created_via'), 'kuitansi', ['created_via'], unique=False)
    op.create_index(op.f('ix_kuitansi_id_rekap_mingguan'), 'kuitansi', ['id_rekap_mingguan'], unique=False)
    op.create_index(op.f('ix_kuitansi_is_finalized'), 'kuitansi', ['is_finalized'], unique=False)
    op.create_index(op.f('ix_kuitansi_nomor_kuitansi'), 'kuitansi', ['nomor_kuitansi'], unique=True)
    op.create_index(op.f('ix_kuitansi_porsi_recomputed_at'), 'kuitansi', ['porsi_recomputed_at'], unique=False)
    op.create_index(op.f('ix_kuitansi_sabat_sesi'), 'kuitansi', ['sabat_sesi'], unique=False)
    op.create_index(op.f('ix_kuitansi_staging_id'), 'kuitansi', ['staging_id'], unique=False)
    op.create_index(op.f('ix_kuitansi_status'), 'kuitansi', ['status'], unique=False)
    op.create_index(op.f('ix_kuitansi_tenant_id'), 'kuitansi', ['tenant_id'], unique=False)
    op.create_index('ix_kuitansi_tenant_nominal', 'kuitansi', ['tenant_id', 'total_pemberian_angka'], unique=False)
    op.create_index('ix_kuitansi_tenant_purged_tanggal', 'kuitansi', ['tenant_id', 'is_purged', 'tanggal_sabat'], unique=False)
    op.create_index('ix_kuitansi_tenant_rekap', 'kuitansi', ['tenant_id', 'id_rekap_mingguan'], unique=False)
    op.create_index('ix_kuitansi_tenant_tanggal', 'kuitansi', ['tenant_id', 'tanggal_sabat'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('related_entity_type', sa.String(length=40), nullable=True),
    sa.Column('related_entity_id', sa.String(length=64), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notif_event_type', 'notifications', ['event_type', 'created_at'], unique=False)
    op.create_index('ix_notif_tenant_created', 'notifications', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_notif_user_unread_created', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_event_type'), 'notifications', ['event_type'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('pengeluaran',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id_rekap_mingguan', sa.String(length=64), nullable=False),
    sa.Column('nomor_pengeluaran', sa.String(length=32), nullable=False),
    sa.Column('tanggal', sa.String(length=16), nullable=False),
    sa.Column('tanggal_sabat', sa.String(length=16), nullable=False),
    sa.Column('kategori_pengeluaran_id', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.BigInteger(), nullable=False),
    sa.Column('deskripsi', sa.String(length=500), nullable=True),
    sa.Column('penerima', sa.String(length=200), nullable=True),
    sa.Column('metode_bayar', sa.String(length=20), nullable=True),
    sa.Column('bukti_path', sa.String(length=255), nullable=True),
    sa.Column('is_purged', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_ketua_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_ketua_at', sa.DateTime(), nullable=True),
    sa.Column('approved_ketua_note', sa.String(length=255), nullable=True),
    sa.Column('approved_pendeta_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_pendeta_at', sa.DateTime(), nullable=True),
    sa.Column('approved_pendeta_note', sa.String(length=255), nullable=True),
    sa.Column('rejected_by_user_id', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_reason', sa.String(length=500), nullable=True),
    sa.Column('created_via', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['approved_ketua_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['approved_pendeta_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kategori_pengeluaran_id'], ['kategori_pengeluaran.id'], ),
    sa.ForeignKeyConstraint(['rejected_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pengeluaran_created_via'), 'pengeluaran', ['created_via'], unique=False)
    op.create_index(op.f('ix_pengeluaran_id_rekap_mingguan'), 'pengeluaran', ['id_rekap_mingguan'], unique=False)
    op.create_index(op.f('ix_pengeluaran_nomor_pengeluaran'), 'pengeluaran', ['nomor_pengeluaran'], unique=True)
    op.create_index(op.f('ix_pengeluaran_status'), 'pengeluaran', ['status'], unique=False)
    op.create_index(op.f('ix_pengeluaran_tanggal_sabat'), 'pengeluaran', ['tanggal_sabat'], unique=False)
    op.create_index(op.f('ix_pengeluaran_tenant_id'), 'pengeluaran', ['tenant_id'], unique=False)
    op.create_index('ix_pengeluaran_tenant_kategori', 'pengeluaran', ['tenant_id', 'kategori_pengeluaran_id'], unique=False)
    op.create_index('ix_pengeluaran_tenant_rekap', 'pengeluaran', ['tenant_id', 'id_rekap_mingguan'], unique=False)
    op.create_index('ix_pengeluaran_tenant_status_tanggal', 'pengeluaran', ['tenant_id', 'status', 'tanggal'], unique=False)
    op.create_index('ix_pengeluaran_tenant_tanggal', 'pengeluaran', ['tenant_id', 'tanggal'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_reason', sa.String(length=64), nullable=True),
    sa.Column('created_ip', sa.String(length=64), nullable=True),
    sa.Column('created_user_agent', sa.String(length=255), nullable=True),
    sa.Column('redeemed_ip', sa.String(length=64), nullable=True),
    sa.Column('redeemed_user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refresh_tenant_active', 'refresh_tokens', ['tenant_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_tenant_id'), 'refresh_tokens', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('ix_refresh_user_active', 'refresh_tokens', ['user_id', 'expires_at'], unique=False)
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_tokens_jti'), 'revoked_tokens', ['jti'], unique=True)
    op.create_index('ix_revoked_tokens_tenant', 'revoked_tokens', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_revoked_tokens_tenant_id'), 'revoked_tokens', ['tenant_id'], unique=False)
    op.create_index('ix_revoked_tokens_user', 'revoked_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_revoked_tokens_user_id'), 'revoked_tokens', ['user_id'], unique=False)
    op.create_table('kuitansi_kategori',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kuitansi_id', sa.Integer(), nullable=False),
    sa.Column('kategori_id', sa.Integer(), nullable=False),
    sa.Column('nominal', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategori_pemasukan.id'], ),
    sa.ForeignKeyConstraint(['kuitansi_id'], ['kuitansi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kuitansi_kategori_kategori', 'kuitansi_kategori', ['kategori_id'], unique=False)
    op.create_index(op.f('ix_kuitansi_kategori_kategori_id'), 'kuitansi_kategori', ['kategori_id'], unique=False)
    op.create_index('ix_kuitansi_kategori_kuitansi', 'kuitansi_kategori', ['kuitansi_id'], unique=False)
    op.create_index(op.f('ix_kuitansi_kategori_kuitansi_id'), 'kuitansi_kategori', ['kuitansi_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kuitansi_kategori_kuitansi_id'), table_name='kuitansi_kategori')
    op.drop_index('ix_kuitansi_kategori_kuitansi', table_name='kuitansi_kategori')
    op.drop_index(op.f('ix_kuitansi_kategori_kategori_id'), table_name='kuitansi_kategori')
    op.drop_index('ix_kuitansi_kategori_kategori', table_name='kuitansi_kategori')
    op.drop_table('kuitansi_kategori')
    op.drop_index(op.f('ix_revoked_tokens_user_id'), table_name='revoked_tokens')
    op.drop_index('ix_revoked_tokens_user', table_name='revoked_tokens')
    op.drop_index(op.f('ix_revoked_tokens_tenant_id'), table_name='revoked_tokens')
    op.drop_index('ix_revoked_tokens_tenant', table_name='revoked_tokens')
    op.drop_index(op.f('ix_revoked_tokens_jti'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_index('ix_refresh_user_active', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_tenant_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_tenant_active', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_pengeluaran_tenant_tanggal', table_name='pengeluaran')
    op.drop_index('ix_pengeluaran_tenant_status_tanggal', table_name='pengeluaran')
    op.drop_index('ix_pengeluaran_tenant_rekap', table_name='pengeluaran')
    op.drop_index('ix_pengeluaran_tenant_kategori', table_name='pengeluaran')
    op.drop_index(op.f('ix_pengeluaran_tenant_id'), table_name='pengeluaran')
    op.drop_index(op.f('ix_pengeluaran_tanggal_sabat'), table_name='pengeluaran')
    op.drop_index(op.f('ix_pengeluaran_status'), table_name='pengeluaran')
    op.drop_index(op.f('ix_pengeluaran_nomor_pengeluaran'), table_name='pengeluaran')
    op.drop_index(op.f('ix_pengeluaran_id_rekap_mingguan'), table_name='pengeluaran')
    op.drop_index(op.f('ix_pengeluaran_created_via'), table_name='pengeluaran')
    op.drop_table('pengeluaran')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_event_type'), table_name='notifications')
    op.drop_index('ix_notif_user_unread_created', table_name='notifications')
    op.drop_index('ix_notif_tenant_created', table_name='notifications')
    op.drop_index('ix_notif_event_type', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_kuitansi_tenant_tanggal', table_name='kuitansi')
    op.drop_index('ix_kuitansi_tenant_rekap', table_name='kuitansi')
    op.drop_index('ix_kuitansi_tenant_purged_tanggal', table_name='kuitansi')
    op.drop_index('ix_kuitansi_tenant_nominal', table_name='kuitansi')
    op.drop_index(op.f('ix_kuitansi_tenant_id'), table_name='kuitansi')
    op.drop_index(op.f('ix_kuitansi_status'), table_name='kuitansi')
    op.drop_index(op.f('ix_kuitansi_staging_id'), table_name='kuitansi')
    op.drop_index(op.f('ix_kuitansi_sabat_sesi'), table_name='kuitansi')
    op.drop_index(op.f('ix_kuitansi_porsi_recomputed_at'), table_name='kuitansi')
    op.drop_index(op.f('ix_kuitansi_nomor_kuitansi'), table_name='kuitansi')
    op.drop_index(op.f('ix_kuitansi_is_finalized'), table_name='kuitansi')
    op.drop_index(op.f('ix_kuitansi_id_rekap_mingguan'), table_name='kuitansi')
    op.drop_index(op.f('ix_kuitansi_created_via'), table_name='kuitansi')
    op.drop_table('kuitansi')
    op.drop_index(op.f('ix_blast_jobs_tenant_id'), table_name='blast_jobs')
    op.drop_index('ix_blast_jobs_rekap', table_name='blast_jobs')
    op.drop_index(op.f('ix_blast_jobs_id_rekap_mingguan'), table_name='blast_jobs')
    op.drop_table('blast_jobs')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sync_outbox_tenant_id'), table_name='sync_outbox')
    op.drop_index('ix_sync_outbox_tenant_created', table_name='sync_outbox')
    op.drop_index(op.f('ix_sync_outbox_payload_hash'), table_name='sync_outbox')
    op.drop_index(op.f('ix_sync_outbox_created_at'), table_name='sync_outbox')
    op.drop_table('sync_outbox')
    op.drop_index(op.f('ix_kategori_pengeluaran_tenant_id'), table_name='kategori_pengeluaran')
    op.drop_index('ix_kategori_pengeluaran_tenant_active', table_name='kategori_pengeluaran')
    op.drop_table('kategori_pengeluaran')
    op.drop_index(op.f('ix_kategori_pemasukan_tenant_id'), table_name='kategori_pemasukan')
    op.drop_index('ix_kategori_pemasukan_tenant_active', table_name='kategori_pemasukan')
    op.drop_table('kategori_pemasukan')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_nomor_kuitansi_token'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id_rekap_mingguan'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_tenants_tenant_signature'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_subdomain'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index('ix_tenant_uni_misi', table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_misi_konferens_uni_id'), table_name='misi_konferens')
    op.drop_table('misi_konferens')
    op.drop_index('ix_wa_sessions_state', table_name='wa_sessions')
    op.drop_index('ix_wa_sessions_expires', table_name='wa_sessions')
    op.drop_table('wa_sessions')
    op.drop_table('uni')
    op.drop_index(op.f('ix_persentase_config_scope'), table_name='persentase_config')
    op.drop_index(op.f('ix_persentase_config_ref_id'), table_name='persentase_config')
    op.drop_table('persentase_config')
    # ### end Alembic commands ###
