#!/bin/bash
# FLIPUS v1.4 — SECRET_KEY Rotation Script
#
# Usage:
#   ./storage/scripts/rotate_secret_key.sh              # Rotate now
#   ./storage/scripts/rotate_secret_key.sh --no-restart  # Rotate, don't restart backend
#
# What it does:
#   1. Generate new SECRET_KEY (cryptographically secure)
#   2. Backup current .env to .env.bak.<timestamp>
#   3. Update .env:
#      - SECRET_KEY = <new>
#      - SECRET_KEY_PREVIOUS = <old> (grace window untuk JWT lama)
#   4. Audit log entry (SECRET_KEY_ROTATED)
#   5. Schedule drop of SECRET_KEY_PREVIOUS after 24 hours
#   6. (Optional) Restart backend
#
# Why dual-key:
#   Saat rotation, user yang masih punya JWT lama tidak akan ter-logout mendak.
#   JWT lama valid via fallback ke SECRET_KEY_PREVIOUS.
#   Setelah 24 jam, SECRET_KEY_PREVIOUS di-drop → only new key valid.

set -e

ENV_FILE=".env"
BACKEND_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$BACKEND_DIR"

if [ ! -f "$ENV_FILE" ]; then
    echo "❌ $ENV_FILE tidak ditemukan di $BACKEND_DIR"
    exit 1
fi

# Generate new key (cryptographically secure, URL-safe base64)
NEW_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(64))")
echo "=== FLIPUS SECRET_KEY Rotation ==="
echo ""
echo "Generated new SECRET_KEY (length: ${#NEW_KEY})"
echo ""

# Backup current .env
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BACKUP_FILE="${ENV_FILE}.bak.${TIMESTAMP}"
cp "$ENV_FILE" "$BACKUP_FILE"
echo "✓ Backup: $BACKUP_FILE"

# Extract old SECRET_KEY value
OLD_KEY=$(grep "^SECRET_KEY=" "$ENV_FILE" | head -1 | cut -d'=' -f2- | tr -d "'\"")
if [ -z "$OLD_KEY" ]; then
    echo "❌ SECRET_KEY tidak ditemukan di $ENV_FILE"
    exit 1
fi

# Update .env: SECRET_KEY = new, SECRET_KEY_PREVIOUS = old (kalau belum ada)
python3 << PYEOF
import re
from pathlib import Path

env_path = Path("$ENV_FILE")
content = env_path.read_text()

old_key = "$OLD_KEY"
new_key = "$NEW_KEY"

# Replace SECRET_KEY= line (first match only)
new_content = re.sub(
    r'^SECRET_KEY\s*=\s*["\\']?[^"\\']*["\\']?',
    f'SECRET_KEY="{new_key}"',
    content,
    count=1,
    flags=re.MULTILINE,
)

# Add or update SECRET_KEY_PREVIOUS (set to old key)
if re.search(r'^SECRET_KEY_PREVIOUS\s*=', new_content, flags=re.MULTILINE):
    new_content = re.sub(
        r'^SECRET_KEY_PREVIOUS\s*=\s*["\\']?[^"\\']*["\\']?',
        f'SECRET_KEY_PREVIOUS="{old_key}"',
        new_content,
        count=1,
        flags=re.MULTILINE,
    )
else:
    # Append after SECRET_KEY line
    new_content = re.sub(
        r'(SECRET_KEY=["\\'][^"\\']*["\\'])',
        f'\\1\\nSECRET_KEY_PREVIOUS="{old_key}"',
        new_content,
        count=1,
    )

env_path.write_text(new_content)
print("✓ .env updated")
PYEOF

echo "✓ SECRET_KEY rotated"
echo "✓ SECRET_KEY_PREVIOUS = (old key, untuk grace window 24 jam)"
echo ""

# Audit log entry (best-effort, tidak block rotasi kalau gagal)
echo "Writing audit log..."
cd "$BACKEND_DIR"
PYTHONPATH=. .venv/bin/python3 << 'PYEOF' 2>/dev/null || echo "  (audit log skipped — run backend then re-attempt)"
import os
from datetime import datetime, timezone
from app.core.database import SessionLocal
from app.models.audit import AuditLog
from app.models.tenant import Tenant

db = SessionLocal()
try:
    first_tenant = db.query(Tenant).first()
    if first_tenant:
        db.add(AuditLog(
            tenant_id=first_tenant.id,
            action="SECRET_KEY_ROTATED",
            payload_hash=f"timestamp_{datetime.now(timezone.utc).isoformat()}",
        ))
        db.commit()
        print("✓ Audit log: SECRET_KEY_ROTATED")
    else:
        print("  (no tenant yet — audit skipped)")
except Exception as e:
    db.rollback()
    print(f"  (audit failed: {e})")
finally:
    db.close()
PYEOF

# Schedule drop of SECRET_KEY_PREVIOUS after 24 hours
SCHEDULE_TIME=$(date -d '+24 hours' +"%M %H %d %m *")
SCRIPT_PATH="$(realpath "$0")"

# Create drop script (referenced by cron)
DROP_SCRIPT="/tmp/flipus_drop_previous_key_${TIMESTAMP}.sh"
cat > "$DROP_SCRIPT" << EOF
#!/bin/bash
# Auto-generated by rotate_secret_key.sh — drop SECRET_KEY_PREVIOUS after grace window
cd "$BACKEND_DIR"
if grep -q "^SECRET_KEY_PREVIOUS=" "$ENV_FILE"; then
    sed -i.bak '/^SECRET_KEY_PREVIOUS=/d' "$ENV_FILE"
    echo "\$(date): SECRET_KEY_PREVIOUS dropped" >> "$BACKEND_DIR/storage/logs/secret_key_rotation.log"
fi
rm -f "$DROP_SCRIPT"
EOF
chmod +x "$DROP_SCRIPT"

# Add cron job (one-shot, will be removed after execution)
(crontab -l 2>/dev/null | grep -v 'flipus_drop_previous_key' ; echo "$SCHEDULE_TIME $DROP_SCRIPT") | crontab -
echo "✓ Cron scheduled: drop SECRET_KEY_PREVIOUS in 24 hours"

# Optional restart
if [ "$1" != "--no-restart" ]; then
    echo ""
    echo "Restarting backend..."
    if [ -f "$BACKEND_DIR/restart_backend.sh" ]; then
        bash "$BACKEND_DIR/restart_backend.sh"
        echo "✓ Backend restarted"
    else
        echo "⚠️  restart_backend.sh tidak ditemukan, restart manual:"
        echo "    pkill -f uvicorn && .venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000 &"
    fi
fi

echo ""
echo "=== Done ==="
echo "Old key ada di $BACKUP_FILE — keep it SECURE untuk audit trail."
echo "Setelah 24 jam, SECRET_KEY_PREVIOUS akan otomatis di-drop."