#!/bin/bash
# FLIPUS v1.4 — HTTPS Setup + Nginx Config Generator
#
# Usage:
#   Production:  sudo ./storage/scripts/setup_https.sh yourdomain.com your-email@example.com
#   Self-signed: sudo ./storage/scripts/setup_https.sh --self-signed localhost
#
# Output:
#   - storage/ssl/fullchain.pem + privkey.pem (self-signed mode)
#   - /etc/letsencrypt/live/<domain>/ (Let's Encrypt mode)
#   - storage/ssl/nginx-flipus.conf (nginx config snippet)
#
# Includes:
#   - TLS 1.2/1.3 with strong ciphers
#   - HTTP → HTTPS redirect (301)
#   - CSP header (defense-in-depth XSS)
#   - HSTS (1 year, includeSubDomains)
#   - Reverse proxy ke uvicorn (port 8000)
#   - Static file serving untuk uploaded files

set -e

DOMAIN=${1:-localhost}
EMAIL=${2:-admin@example.com}

echo "=== FLIPUS v1.4 HTTPS + CSP Setup ==="
echo "Domain: $DOMAIN"
echo "Email:  $EMAIL"
echo ""

mkdir -p storage/ssl

# Check certbot
if ! command -v certbot &> /dev/null; then
    echo "❌ certbot belum terinstall"
    echo "Install: sudo apt install certbot python3-certbot-nginx"
    exit 1
fi

# Self-signed mode (development/staging)
if [ "$DOMAIN" = "--self-signed" ]; then
    DOMAIN=${2:-localhost}
    echo "📜 Generating self-signed cert untuk development ($DOMAIN)..."
    openssl req -x509 -nodes -days 365 \
        -newkey rsa:2048 \
        -keyout storage/ssl/privkey.pem \
        -out storage/ssl/fullchain.pem \
        -subj "/CN=$DOMAIN" \
        2>/dev/null

    echo "✓ Self-signed cert generated:"
    echo "  - storage/ssl/fullchain.pem"
    echo "  - storage/ssl/privkey.pem"
    CERT_PATH="$(pwd)/storage/ssl/fullchain.pem"
    KEY_PATH="$(pwd)/storage/ssl/privkey.pem"
    SELF_SIGNED=true
else
    # Production mode dengan Let's Encrypt
    echo "🌐 Getting Let's Encrypt cert untuk $DOMAIN..."

    # Stop nginx kalau running (certbot perlu port 80)
    if command -v systemctl &> /dev/null; then
        sudo systemctl stop nginx 2>/dev/null || true
    fi

    # Generate cert (standalone mode, no nginx plugin)
    sudo certbot certonly --standalone \
        --preferred-challenges http \
        -d "$DOMAIN" \
        --email "$EMAIL" \
        --agree-tos \
        --no-eff-email

    CERT_PATH="/etc/letsencrypt/live/$DOMAIN/fullchain.pem"
    KEY_PATH="/etc/letsencrypt/live/$DOMAIN/privkey.pem"
    SELF_SIGNED=false
fi

# ===== Generate nginx config snippet (HTTPS + CSP + reverse proxy) =====
cat > storage/ssl/nginx-flipus.conf << EOF
# FLIPUS v1.4 — Nginx config untuk $DOMAIN
# Generated by setup_https.sh
#
# Install:
#   sudo cp storage/ssl/nginx-flipus.conf /etc/nginx/sites-available/flipus
#   sudo ln -sf /etc/nginx/sites-available/flipus /etc/nginx/sites-enabled/flipus
#   sudo nginx -t && sudo systemctl reload nginx

# HTTP → HTTPS redirect
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN;

    # Allow Let's Encrypt renewal
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://\$server_name\$request_uri;
    }
}

# HTTPS server
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name $DOMAIN;

    ssl_certificate $CERT_PATH;
    ssl_certificate_key $KEY_PATH;

    # ===== TLS hardening =====
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;
    ssl_stapling on;
    ssl_stapling_verify on;

    # ===== Security headers (CSP + HSTS + clickjacking protection) =====
    # CSP: izinkan assets dari self + inline styles (FLIPUS pakai inline styles untuk anti-Tailwind misconfig)
    add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; form-action 'self'; base-uri 'self'" always;

    # HSTS: 1 tahun, include subdomain
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # Anti-clickjacking
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;

    # ===== Reverse proxy ke backend (uvicorn) =====
    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        # WebSocket support (untuk notification center)
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # ===== Static files (uploaded logos, OCR, dll) =====
    location /storage/ {
        alias $(pwd)/storage/;
        expires 30d;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    # Upload size limit (logo max 1MB)
    client_max_body_size 2M;

    # Rate limiting zone (basic)
    limit_req_zone \$binary_remote_addr zone=flipus_login:10m rate=10r/m;
    limit_req zone=flipus_login burst=20 nodelay;

    # Logging
    access_log /var/log/nginx/flipus_access.log;
    error_log /var/log/nginx/flipus_error.log;
}
EOF

echo ""
echo "✓ Nginx config generated: storage/ssl/nginx-flipus.conf"
echo ""

# Auto-renewal cron (production only)
if [ "$SELF_SIGNED" = false ]; then
    echo "Setting up auto-renewal cron..."
    (sudo crontab -l 2>/dev/null | grep -v 'certbot renew' ; echo "0 3 * * * certbot renew --quiet --post-hook 'systemctl reload nginx'") | sudo crontab -
    echo "✓ Auto-renewal cron installed (03:00 daily)"
fi

echo ""
echo "=== Next steps ==="
echo "1. Review config: cat storage/ssl/nginx-flipus.conf"
echo "2. Install ke nginx:"
echo "   sudo cp storage/ssl/nginx-flipus.conf /etc/nginx/sites-available/flipus"
echo "   sudo ln -sf /etc/nginx/sites-available/flipus /etc/nginx/sites-enabled/flipus"
echo "   sudo nginx -t"
echo "   sudo systemctl reload nginx"
echo "3. Pastikan backend (uvicorn) running di port 8000"
echo "4. Test HTTPS: curl -I https://$DOMAIN/"
echo ""
if [ "$SELF_SIGNED" = true ]; then
    echo "⚠️  Self-signed cert — browser akan warning. Untuk production, run tanpa --self-signed."
fi